services:
  comfyui:
    init: true
    container_name: comfyui-wd
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: "warpdriven/comfyui-boot"
    image: "yanwk/comfyui-boot:latest"
    networks:
      wd_ai_net:
        ipv4_address: 172.18.0.30
    ports:
      - "8188:8188"
    volumes:
      - "/data_lake/comfyui_storage:/home/runner"
    environment:
      - CLI_ARGS=
    security_opt:
      - "label=type:nvidia_container_t"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
networks:
    wd_ai_net:
      name: wd_ai_net
      driver: bridge
      ipam:
          driver: default
          config:
            - subnet: 172.18.0.0/24
              gateway: 172.18.0.1
