name: Publish 'megapak' to Docker Hub

on: 
  workflow_dispatch: # Can be manually triggered
  schedule: # Runs on every Monday, 07:00 UTC
    - cron: '0 7 * * 1'
  push: 
    branches: [ main ]
    paths-ignore:
      - '**'
      - '!megapak/Dockerfile'
      - '!megapak/builder-scripts/**'
      - '!megapak/runner-scripts/**'
      - '!.github/workflows/build-megapak.yml'

jobs:

  build-publish-megapak:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'true'
          remove-android: 'true'
      - 
        name: Git checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      -
        name: Build and push 'megapak'
        uses: docker/build-push-action@v6
        with:
          context: ./megapak
          file: ./megapak/Dockerfile
          tags:  |
            yanwk/comfyui-boot:megapak
            yanwk/comfyui-boot:megapak-${{ steps.date.outputs.date }}
          push: true
